--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event fires when an actor has determined an action in a combat session. The action chosen is `session.selectedAction`, which can be changed to affect the actor AI. Note that other data in `e.session` like `selectedWeapon` or `selectedMagic` is only indicative of the AI's choice. The weapon or magic that the actor uses must be set on the mobile.
--- @class determinedActionEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field session tes3combatSession *Read-only*. The combat session the action has been determined for.
