--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event is triggered before a magic reflection check. It allows changing the reflection chance. Note that some magic effects that the player casts are unreflectable (usually non-damage effects, see magic effect flags) and do not trigger this event.
--- 	
--- Each reflect effect active on a target will roll separately; the reflect chances are independent. This event also occurs once per effect in a spell, so a multi-effect spell may trigger this multiple times.
--- @class magicReflectEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field mobile tes3mobileActor|tes3mobileCreature|tes3mobileNPC|tes3mobilePlayer *Read-only*. The mobile actor that may reflect the spell.
--- @field reflectChance number The % chance that the magic is reflected. May be modified.
--- @field reflectEffect tes3activeMagicEffect *Read-only*. The specific reflect effect being tested. This is a `tes3activeMagicEffect` instead of a more common magic instance. You can lookup the magic source instance or effect instance with `tes3activeMagicEffect` accessors.
--- @field source tes3alchemy|tes3enchantment|tes3spell *Read-only*. The magic source.
--- @field sourceInstance tes3magicSourceInstance *Read-only*. The unique instance of the magic source.
--- @field target tes3reference *Read-only*. The actor that may reflect the spell.
