--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event fires when a button on the mouse is pressed.
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/events/mouseButtonDown).
--- @class mouseButtonDownEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field button integer *Read-only*. The button index that was pressed.
--- @field isAltDown boolean *Read-only*. True if alt is held.
--- @field isControlDown boolean *Read-only*. True if control is held.
--- @field isShiftDown boolean *Read-only*. True if either shift key is held.
--- @field isSuperDown boolean *Read-only*. True if super (Windows key) is held.
