--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- The `musicChangeTrack` event when the game is changing to play a new piece of music.
--- @class musicChangeTrackEventData
--- @field block boolean If set to `true`, vanilla logic will be suppressed. Returning `false` will set this to `true`.
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field context string *Read-only*. A short lowercase string that describes why the music is being played, to give more context. `explore` and `combat` values mean the game has chosen a new background music to play. `title` will play (and loop) on the main menu. `level` will play whenever the player has rested and is ready to level up. `mwscript` means a script has used the `StreamMusic` mwscript command. `death` means the player has died. `lua` means that a lua script has requested new music.
--- @field crossfade number The number of milliseconds of crossfade that will be used to blend the current music to the new music.
--- @field music string The track that will be played. This can be changed to a new path, but it must be valid. Note that unlike the `musicSelectTrack` event, this value is not relative to `Data Files\music`.
--- @field situation tes3.musicSituation *Read-only*. Maps to [`tes3.musicSituation`](https://mwse.github.io/MWSE/references/music-situations/), indicating combat, non-combat, or scripted music.
--- @field volume number The volume of the track to be played, ranging from `0.0` to `1.0`. This can be modified.
