--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event fires when the player attempts to pickpocket an item stack, and also on closing the pickpocket contents window. When the window is closed, `item` will be `nil`.
--- @class pickpocketEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field chance number The % chance the pickpocket attempt will be successful.
--- @field count number *Read-only*. The count of items in the chosen stack.
--- @field item tes3alchemy|tes3apparatus|tes3armor|tes3book|tes3clothing|tes3ingredient|tes3item|tes3light|tes3lockpick|tes3misc|tes3probe|tes3repairTool|tes3weapon|nil *Read-only*. The chosen item. `nil` when the window is being closed.
--- @field itemData tes3itemData|nil *Read-only*. The chosen item data. `nil` when the window is being closed.
--- @field mobile tes3mobileActor|tes3mobileCreature|tes3mobileNPC|tes3mobilePlayer *Read-only*. The mobile actor being pickpocketed.
--- @field reference tes3reference *Read-only*. The reference of the actor being pickpocketed.
