-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- This event fires once the player arrives at a travel destination via a travel service.
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/events/travelFinished).
--- @class travelFinishedEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field basePrice number *Read-only*. The base cost of traveling the service.
--- @field cell tes3cell *Read-only*. The destination cell of the travel.
--- @field companions tes3mobileActor[]|tes3mobileCreature[]|tes3mobileNPC[]|tes3mobilePlayer[]|nil *Read-only*. Companions that have traveled with the player, or `nil` if no companions were present.
--- @field destination tes3reference *Read-only*. The travel marker that marks the destination at which the player arrived at.
--- @field hoursPassed number *Read-only*. The time passed during travel, in hours.
--- @field mobile tes3mobileActor|tes3mobileCreature|tes3mobileNPC|tes3mobilePlayer *Read-only*. The mobile actor of the merchant that transported the player.
--- @field previousCell tes3cell *Read-only*. The starting cell of the travel.
--- @field price number *Read-only*. The actual cost of the service.
--- @field reference tes3reference *Read-only*. The mobile’s related reference.
