--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- The uiSkillTooltip event triggers when a new tooltip is displayed for a skill. The tooltip will be already be built.
--- 
--- Note that tooltips may have different width depending on which menu they were created in, between 230 and 432 pixels by default.
--- 	
--- @class uiSkillTooltipEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field creator tes3uiElement? *Read-only*. The UI element, if applicable, that created this tooltip.
--- @field skill tes3.skill *Read-only*. The id of the skill being examined.
--- @field tooltip tes3uiElement *Read-only*. The newly created tooltip element. Due to timeouts and target changes, it may be destroyed at any time.
--- @field type integer *Read-only*. 1 where the tooltip is being created by MenuStat, and includes progress to the next skill level up, and 0 for every other instance including tes3ui.createTooltipMenu().
