--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event is called prior to adding body parts to for a piece of equipment (armor or clothing).
--- @class updateBodyPartsForItemEventData
--- @field block boolean If set to `true`, vanilla logic will be suppressed. Returning `false` will set this to `true`.
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field bodyPartManager tes3bodyPartManager *Read-only*. `reference`'s body part manager.
--- @field isFemale boolean *Read-only*. If true, the reference is female.
--- @field isFirstPerson boolean *Read-only*. If true, the reference is first person.
--- @field item tes3alchemy|tes3apparatus|tes3armor|tes3book|tes3clothing|tes3ingredient|tes3item|tes3light|tes3lockpick|tes3misc|tes3probe|tes3repairTool|tes3weapon The item whose parts will be used. This can be changed to provide an override. Note that items must be of the same type (i.e. armor to armor, but not armor to clothing).
--- @field reference tes3reference *Read-only*. Whose body parts are being built for the given item.
