--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- The table returned by [`mgeWeatherConfig:getPerPixelLighting`](https://mwse.github.io/MWSE/types/mgeWeatherConfig/).
--- @class mgePerPixelLightingTable
--- @field ambient number Corresponds to the value of "Ambient brightness multiplier" setting for given weather in the Per-pixel Lighting Settings menu of MGE XE.
--- @field sun number Corresponds to the value of "Sun brightness multiplier" setting for given weather in the Per-pixel Lighting Settings menu of MGE XE.
--- @field weather tes3.weather The weather type passed to the `getPerPixelLighting` method. Maps to values in [`tes3.weather`](https://mwse.github.io/MWSE/references/weather-types/) table.
