--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A loaded MGE shader.
--- @class mgeShaderHandle
--- @field enabled boolean The enabled state of the shader.
--- @field name string The shader name.
--- @field orderPriority integer The calculated ordering priority value of the shader, that allows auto-sorting of shaders. Changing this value will re-sort the shader list.
--- @field variables table<string, string> Lists the shader's editable variables. The result table has the variable names as keys, and the variable types as values. To get and set the actual variable, use the expression `shaderHandle.<variableName>`.
--- 
--- Variable types are:
--- 
--- - 'b' boolean
--- - 'i' integer
--- - 'f' float
--- - 's' string
--- - 'B' boolean array
--- - 'I' integer array
--- - 'F' float array (was 'a' for MGE v0.16.x and earlier)
--- - '2' vec2
--- - '3' vec3
--- - '4' vec4
--- - 'V' vec4 array
--- - 'm' matrix
mgeShaderHandle = {}

--- Serializes the object to json.
--- @return string result No description yet available.
function mgeShaderHandle:__tojson() end

--- Serializes the object to string.
--- @return string result No description yet available.
function mgeShaderHandle:__tostring() end

--- Reloads and recompiles the shader. Returns if the reload was successful.
--- @return boolean success No description yet available.
function mgeShaderHandle:reload() end

