--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- The table returned by [`mgeWeatherConfig:getScattering`](https://mwse.github.io/MWSE/types/mgeWeatherConfig/).
--- @class mgeScatteringTable
--- @field inscatter number[] The three in-scatter values from MGE.
--- @field outscatter number[] The three out-scatter values from MGE.
