--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise a mwseMCMTextField.
--- @class mwseMCMTextFieldElements : mwseMCMComponentElements
--- @field border tes3uiElement Holds a thin border UI element.
--- @field inputField tes3uiElement Holds a text input UI element.
--- @field submitButton tes3uiElement Holds a button UI element.
