--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise a mwseMCMMouseOverPage.
--- @class mwseMCMMouseOverPageElements : mwseMCMCategoryElements, mwseMCMComponentElements
--- @field mouseOverBlock tes3uiElement A block UI element that shows the description of the component that the mouse is currently hovering over in Sidebar Pages. Replaces the `subcomponentsContainer` element during this time.
--- @field subcomponentsContainer tes3uiElement This the parent UI element for all the components in the Sidebar Page right column in the default view.
