--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds the UI elements that comprise a search bar in Exclusions Page.
--- @class mwseMCMExclusionsPageSearchBarElements
--- @field leftList tes3uiElement 
--- @field rightList tes3uiElement 
