--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise a mwseMCMColorPickerButton.
--- @class mwseMCMColorPickerButtonElements : mwseMCMComponentElements
--- @field button tes3uiElement The Choose button UI element.
--- @field preview tes3uiElement The color preview UI element.
