--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A Lua table with RGB color values.
--- @class mwseColorTable
--- @field b number The blue value. In range [0, 1].
--- @field g number The green value. In range [0, 1].
--- @field r number The red value. In range [0, 1].
