--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise a mwseMCMPage.
--- @class mwseMCMPageElements : mwseMCMCategoryElements, mwseMCMComponentElements
--- @field resetButton tes3uiElement This is the Reset button UI element.
--- @field resetContainer tes3uiElement This is the parent UI element for the Page's Reset button.
