--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A list of valid logging levels.
--- @class mwseLogger.LOG_LEVEL
