--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A table with the data about mouse and keyboard key combination. Unbound key combinations will have all the fields set to `nil`.
--- @class mwseKeyMouseCombo : mwseKeyCombo
--- @field mouseButton integer|false|nil The index of the currently pressed mouse button.
--- @field mouseWheel integer|false|nil The mouse wheel action in the combination.
--- 
--- Value | Description
--- ----- | ----------------
--- -1    | Mouse wheel down
---  1    | Mouse wheel up
--- 
