--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise a mwseMCMButton.
--- @class mwseMCMButtonElements : mwseMCMComponentElements
--- @field button tes3uiElement This is the button UI element.
