--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise a mwseMCMCategory.
--- @class mwseMCMCategoryElements : mwseMCMComponentElements
--- @field subcomponentsContainer tes3uiElement This is the parent UI element for all the UI elements of MCM components that are in this Category.
