--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise a mwseMCMSideBarPage.
--- @class mwseMCMSideBarPageElements : mwseMCMCategoryElements, mwseMCMComponentElements
--- @field mouseOver mwseMCMActiveInfo|mwseMCMMouseOverInfo This page is the right column of the Sidebar Page. It shows the Infos/Settings added to it in the default view. While the mouse if hovering over a component on the left column of the Sidebar Page, this page shows the description of the hovered component instead.
--- @field sideToSideBlock tes3uiElement The sideToSideBlock is the parent UI element for the left and right columns of the Sidebar Page.
