--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise a mwseMCMDropdown.
--- @class mwseMCMDropdownElements : mwseMCMComponentElements
--- @field border tes3uiElement The border UI element of the top part of Dropdown.
--- @field dropdown tes3uiElement A thin border UI element that holds the text select entries of the expanded dropdown.
--- @field dropdownParent tes3uiElement A parent block UI element that holds the expanded dropdown.
--- @field textBox tes3uiElement The text select UI element of the top part of Dropdown.
