--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- The lua environment for the dialogue scripting. It's used in [dialogueEnvirnometCreated](https://mwse.github.io/MWSE/events/dialogueEnvironmentCreated/) event. Any data or functions added to this table will be available as global variables to dialogue scripts.
--- @class mwseDialogueEnvironment
--- @field dialogue tes3dialogue The dialogue this `dialogueEnvironmentCreated` event was triggered from.
--- @field info tes3dialogue The dialogue info this `dialogueEnvironmentCreated` event was triggered from.
--- @field noMorrowindScript boolean Setting this value to true will block the original dialogue result script from running. By default, it is set to false.
--- @field reference tes3reference The script target reference. That's the NPC or creature the player is speaking with.
