--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise an Exclusions Page.
--- @class mwseMCMExclusionsPageElements : mwseMCMCategoryElements, mwseMCMComponentElements
--- @field description tes3uiElement|nil A label UI element with the Exclusions Page's description as text.
--- @field filterList tes3uiElement|nil A block UI element that holds a button for each of the filters of Exclusions Page. If there is only one filter, this UI element won't be visible.
--- @field leftList tes3uiElement|nil A vertical scroll pane UI element for all the items on the left list.
--- @field rightList tes3uiElement|nil A vertical scroll pane UI element for all the items on the right list.
--- @field searchBar mwseMCMExclusionsPageSearchBarElements|nil 
--- @field searchBarInput mwseMCMExclusionsPageSearchBarElements|nil 
--- @field sections tes3uiElement|nil A block UI element that holds the `leftList`, `rightList` and `filterList` UI element trees.
