--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This dictionary-style table holds all of the UI elements that comprise a mwseMCMComponent.
--- @class mwseMCMComponentElements
--- @field innerContainer tes3uiElement|nil The innerContainer adds `self.indent` additional padding on the left if the component has a label.
--- @field label tes3uiElement|nil Holds component's label UI element. Not all component types have a label.
--- @field labelBlock tes3uiElement|nil Holds a block UI element, inside which label is found.
--- @field outerContainer tes3uiElement|nil The top UI element for this component. All the other UI elements that comprise a component are children of this element.
