--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A simple bounding sphere. Used for coarse visibility and intersection tests.
--- @class niBound
--- @field center tes3vector3 The coordinates of the bounds center. It may be relative to the object, or in world coordinates, depending on how the bound is used.
--- @field radius number The radius of the bounds.
