--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A subclass of `niNode` that synchronizes animation timing and updates when placed in a subtree under an `niBSAnimationManager`.
--- @class niBSAnimationNode : niNode, niAVObject, niObjectNET, niObject
niBSAnimationNode = {}

--- Creates a new, empty NiBSAnimationNode.
--- @return niBSAnimationNode|niBSParticleNode node No description yet available.
function niBSAnimationNode.new() end

