--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A subclass of `niBSAnimationNode` that optionally pins child nodes to world space. Intended for world space particle systems.
--- @class niBSParticleNode : niBSAnimationNode, niNode, niAVObject, niObjectNET, niObject
--- @field followMode boolean Controls if the node and its children follow the parent, or is they are anchored in world space at their initial position. This flag must be set before the first update.
niBSParticleNode = {}

--- Creates a new, empty NiBSParticleNode.
--- @return niBSParticleNode node No description yet available.
function niBSParticleNode.new() end

