--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A structure containing properties specific to tab containers.
--- @class tes3uiTabContainer : tes3uiWidget
--- @field currentTab string The ID of the currently selected tab. Setting this value will change to the tab associated with the ID.
tes3uiTabContainer = {}

--- Creates a new tab in the container. This will add a tab button to the top of the element, as well as a new block for the contents, which will be returned.
--- @param params tes3uiTabContainer.addTab.params This table accepts the following values:
--- 
--- `id`: string — The unique identifier for the tab.
--- 
--- `name`: string? — *Optional*. The text used for the tab's selector button. If not provided, the ID will be used.
--- @return tes3uiElement result No description yet available.
function tes3uiTabContainer:addTab(params) end

---Table parameter definitions for `tes3uiTabContainer.addTab`.
--- @class tes3uiTabContainer.addTab.params
--- @field id string The unique identifier for the tab.
--- @field name string? *Optional*. The text used for the tab's selector button. If not provided, the ID will be used.

--- Gets the block that contains the tab contents used for this container. Should be used with care.
--- @return tes3uiElement result No description yet available.
function tes3uiTabContainer:getContentsBlock() end

--- Gets the block that contains the tab buttons used for this container. Should be used with care.
--- @return tes3uiElement result No description yet available.
function tes3uiTabContainer:getTabsBlock() end

