--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A substructure for a race, storing up to 7 skill bonuses.
--- @class tes3raceSkillBonus
--- @field bonus number The value to modify the skill with.
--- @field skill tes3.skill The skill id to modify. Maps to values in [`tes3.skill`](https://mwse.github.io/MWSE/references/skills/) namespace.
