--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A structure that contains weather information for the rain weather type.
--- @class tes3weatherRain : tes3weather
--- @field maxParticles number The weather's maximum particles.
--- @field particleEntranceSpeed number The weather's particle entrance speed.
--- @field particleHeightMax number The weather's particle maximum height.
--- @field particleHeightMin number The weather's particle minimum height.
--- @field particleRadius number The weather's particle radius.
--- @field rainActive boolean *Read-only*. The weather's active rain flag.
--- @field rainLoopSound tes3sound The weather's rain loop sound object. This value is only modifiable for legacy compatibility. The current rain sound should be changed by setting `rainLoopSoundId`.
--- @field rainLoopSoundId string The weather's rain loop sound ID. This can be changed, and the sound will switch over when the weather is active
--- @field threshold number The weather's threshold value.
