--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A game object that stores animation group data from loaded keyframe data. This includes action and sound timing. Animation groups belonging to the same animation file are linked together.
--- @class tes3animationGroup
--- @field actionCount number *Read-only*. The number of action note keys.
--- @field actionFrames number[] *Read-only*. The action frame numbers array. The available action indexes depend on the purpose of the animation group.
--- @field actionTimings number[] *Read-only*. The action frame timings array. The available action indexes depend on the purpose of the animation group.
--- @field groupId number *Read-only*. The animation group ID. Useful when iterating through groups using nextGroup.
--- @field nextGroup tes3animationGroup *Read-only*. The next animation group in this keyframe data.
--- @field soundGenCount number *Read-only*. The number of soundgen note keys.
--- @field soundGenKeys tes3animationGroupSoundGenKey[] *Read-only*. An array containing the soundgens.
