--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- An apparatus game object.
--- @class tes3apparatus : tes3item, tes3physicalObject, tes3object, tes3baseObject
--- @field quality number The quality of the apparatus.
--- @field script tes3script The script that runs on the object.
--- @field type tes3.apparatusType The type of the apparatus. Maps to values in [`tes3.apparatusType`](https://mwse.github.io/MWSE/references/apparatus-types/) namespace.
--- @field value number The value of the object.
--- @field weight number The weight of the object.
