--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A table with all the textures used by a color picker widget.
--- @class tes3uiColorPickerTextureTable
--- @field alpha niSourceTexture The texture for the alpha bar.
--- @field hue niSourceTexture The texture for the hue bar.
--- @field main niSourceTexture The texture for the main picker.
--- @field saturation niSourceTexture The texture for the saturation bar.
