--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- The table passed to the callback function in `tes3.messageBox`.
--- @class tes3messageBoxCallbackData
--- @field button integer *Read-only*. A 0-based index of the selected button from the buttons array passed when calling `tes3.messageBox`.
