--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- The table passed to `tes3ui.showInventorySelectMenu` function's filter function.
--- @class tes3ui.showInventorySelectMenu.filterParams
--- @field item tes3alchemy|tes3apparatus|tes3armor|tes3book|tes3clothing|tes3ingredient|tes3item|tes3light|tes3lockpick|tes3misc|tes3probe|tes3repairTool|tes3weapon The item that is being filtered.
--- @field itemData tes3itemData|nil The item data of the item that is being filtered.
