--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- Almost anything that can be represented in the Construction Set is based on this structure.
--- @class tes3physicalObject : tes3object, tes3baseObject
--- @field boundingBox tes3boundingBox The bounding box for the object.
