--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A sound generator object created in the TES3 CS
--- @class tes3soundGenerator : tes3baseObject
--- @field creature tes3creature|nil The base creature for this soundgen, which serves as a lookup index. Note that creatures can reference the soundgen of any other creature through the `tes3creature.soundCreature` property, which is generally used for variants of a creature.
--- 
--- When this is nil, the sound is treated as a generic fallback for this soundGen type, which is played when there is no creature match.
--- @field sound tes3sound Sound object tied to this sound generator.
--- @field type tes3.soundGenType Maps to [`tes3.soundGenType`](https://mwse.github.io/MWSE/references/sound-generator-types/) constants.
tes3soundGenerator = {}

--- Serializes the object to json.
--- @return string result No description yet available.
function tes3soundGenerator:__tojson() end

