-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- This table is passed to the `onCollision` callback function in a custom magic effect.
--- @class tes3magicEffectCollisionEventData
--- @field collision tes3mobileObjectCollision The collision data.
--- @field effectId integer Maps to values in [`tes3.effect`](https://mwse.github.io/MWSE/references/magic-effects/) table.
--- @field effectIndex integer The index of the effect in the spell.
--- @field sourceInstance tes3magicSourceInstance Access to the magic source of the effect instance.
