--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A structure that contains weather information for the foggy weather type.
--- @class tes3weatherFoggy : tes3weather
