--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A structure that contains weather information for the ashstorm weather type.
--- @class tes3weatherAsh : tes3weather
--- @field stormOrigin tes3vector2 The origin point of weather particles. The storm will appear to blow outwards from this point.
--- @field threshold number The weather's threshold value.
