--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A container object that has been cloned. Typically represents a container that has been instanced by being opened by the player.
--- @class tes3containerInstance : tes3actor, tes3physicalObject, tes3object, tes3baseObject
--- @field baseObject tes3container *Read-only*. The base container object that the instance inherits from.
--- @field isInstance boolean Always returns true.
--- @field mesh string The path to the object's mesh.
--- @field name string The player-facing name for the object.
--- @field organic boolean Determines if the container's organic flag is enabled. The name of this property comes from the Construction Set. If a container is flagged as organic, no items can be stored inside such containers. In vanilla, those are all plants, mushrooms, and ores. In addition, resupplying guild supply chests are implemented as organic and respawning containers.
--- @field reference tes3reference *Read-only*. The reference that the object is represented by.
--- @field respawns boolean Determines if the container's respawn flag is enabled. Only the organic containers can have respawn flag set.
--- 
--- The global script variable, "MonthsToRespawn" is decremented at the end of each month. If it reaches zero at the first day of next month, it is reset to `iMonthsToRespawn` (GMST) and all respawning containers are refilled.
--- @field script tes3script *Read-only*. The script that runs on the object.
