-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- A script context object, which allows variables to be get/set using the variable name.
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/types/tes3scriptContext).
--- @class tes3scriptContext
--- @operator len: number
tes3scriptContext = {}

--- This method fetches all of the script's variables as a table.
--- @return table<string, tes3scriptVariableData> results A table with all of the script's variable names as keys.
function tes3scriptContext:getVariableData() end

