--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- The table passed to `tes3ui.showInventorySelectMenu` function's callback.
--- @class tes3ui.showInventorySelectMenu.callbackParams
--- @field actor tes3actor|tes3container|tes3containerInstance|tes3creature|tes3creatureInstance|tes3npc|tes3npcInstance The actor containing the inventory.
--- @field count integer The number of items that have been selected. Only valid if `item` is not `nil`.
--- @field inventory tes3inventory The inventory containing the items.
--- @field item tes3alchemy|tes3apparatus|tes3armor|tes3book|tes3clothing|tes3ingredient|tes3item|tes3light|tes3lockpick|tes3misc|tes3probe|tes3repairTool|tes3weapon|nil The item that has been selected.
--- @field itemData tes3itemData|nil The item data of the item that has been selected.
