--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- Returns the type of a given lua variable. It also provides the name of userdata variables.
--- @param variable any The variable to get the type of.
--- @return string type The base type of the variable.
--- @return string|nil userdataType The userdata type of the variable.
function type(variable) end

