site_name: Morrowind Script Extender

docs_dir: source

repo_url: https://github.com/MWSE/MWSE

plugins:
  - awesome-pages
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
      enabled: !ENV [CI, false]
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'
  - search:
      # Default search is quite bad. Try with a better token separator. Taken directly from:
      # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#+search.separator
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])'

extra_javascript:
  - assets/js/reloadMermaidPagesOnPaletteSwitch.js

extra_css:
  - assets/mwse.css

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/square-github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate           # With API lists, this is not useful. Instead break the navigation into two sections.

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: includes
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tilde
  - toc:
      permalink: ⚓︎
      toc_depth: 3
