--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- Convenience access to frame timer functions. This is the same as passing `type = timer.real` to any of the functions from timer API.
--- @class timer.framelib
timer.frame = {}

--- Creates a timer that will finish the next frame.
--- 
--- !!! tip
--- 	It's recommended to study the [Object Lifetimes](../guides/object-lifetimes.md) guide. It describes how to safely use [tes3reference](../types/tes3reference.md) objects inside timer callbacks.
--- @param callback fun(e: mwseTimerCallbackData) The callback function that will execute when the timer expires.
--- @return mwseTimer timer No description yet available.
function timer.frame.delayOneFrame(callback) end

